create table person
(
    id         int generated by default as identity primary key,
    username   varchar(30) not null unique,
    first_name varchar(15) not null,
    last_name  varchar(15) not null,
    password   varchar     not null,
    email      varchar     not null unique,
    role       varchar
);
create table product
(
    id          int generated by default as identity primary key,
    name        varchar not null,
    description text    not null,
    count_left  int check ( count_left > -1 ),
    price       decimal not null default 0,
    photo       bytea
);
CREATE TABLE orders
(
    id               SERIAL PRIMARY KEY,
    status           VARCHAR(50)  NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    shipping_address VARCHAR(255) NOT NULL,
    person_id        int references person (id)
);
create table cart_item
(
    id         int generated by default as identity primary key,
    username   varchar references person (username) not null,
    product_id int references product (id)          not null,
    quantity   int check ( quantity > 0 )           not null,
    order_id   int references orders (id) on delete cascade
);


